Update documentation.yml

diff --git a/.github/workflows/documentation.yml b/.github/workflows/documentation.yml
--- a/.github/workflows/documentation.yml
+++ b/.github/workflows/documentation.yml
@@ -1,50 +1,50 @@
 name: Update documentation webpage
 
 on:
-  push:
-    branches:    
-      - master
+    push:
+        branches:
+            - master
 
 jobs:
-  build:
+    build:
+        runs-on: ubuntu-latest
 
-    runs-on: ubuntu-latest
+        steps:
+            - uses: actions/checkout@v3
+            - name: Set up Python
+              uses: actions/setup-python@v3
+              with:
+                  python-version: "3.x"
 
-    steps:
-   
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.x'
-    - uses: actions/checkout@v1
-    - name: Install dependencies and build docs
-      run: |
-        cd docs
-        python -m pip install -r requirements.txt
-        make html
+            - name: Install dependencies and build docs
+              run: |
+                  cd docs
+                  python -m pip install -r requirements.txt
+                  make html
 
-    # Create an artifact of the html output.
-    - uses: actions/upload-artifact@v1
-      with:
-        name: DocumentationHTML
-        path: docs/_build/html/
-    # Publish built docs to gh-pages branch.
-    # ===============================
-    - name: Commit documentation changes
-      run: |
-        git clone https://github.com/RealityBending/Pyllusion.git --branch gh-pages --single-branch gh-pages
-        cp -r docs/_build/html/* gh-pages/
-        cd gh-pages
-        git config --local user.email "phamttam17@gmail.com"
-        git config --local user.name "Tam-Pham"
-        git add .
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # that.
-    - name: Push changes
-      uses: ad-m/github-push-action@master
-      with:
-        branch: gh-pages
-        directory: gh-pages
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-    # ===============================
+            # Create an artifact of the html output.
+            - uses: actions/upload-artifact@v1
+              with:
+                  name: DocumentationHTML
+                  path: docs/_build/html/
+
+            # Publish built docs to gh-pages branch.
+            # ===============================
+            - name: Commit documentation changes
+              run: |
+                  git clone https://github.com/RealityBending/Pyllusion.git --branch gh-pages --single-branch gh-pages
+                  cp -r docs/_build/html/* gh-pages/
+                  cd gh-pages
+                  git config --local user.email "phamttam17@gmail.com"
+                  git config --local user.name "Tam-Pham"
+                  git add .
+                  git commit -m "Update documentation" -a || true
+                  # The above command will fail if no changes were present, so we ignore
+                  # that.
+            - name: Push changes
+              uses: ad-m/github-push-action@master
+              with:
+                  branch: gh-pages
+                  directory: gh-pages
+                  github_token: ${{ secrets.GITHUB_TOKEN }}
+        # ===============================
